// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAlive.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageAlive.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageAlive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageAlive_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageAlive_2eproto() {
  protobuf_AddDesc_MessageAlive_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageAlive.proto");
  GOOGLE_CHECK(file != NULL);
  MessageAlive_descriptor_ = file->message_type(0);
  static const int MessageAlive_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, cpu_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, memory_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, blockcount_),
  };
  MessageAlive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageAlive_descriptor_,
      MessageAlive::default_instance_,
      MessageAlive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageAlive));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageAlive_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageAlive_descriptor_, &MessageAlive::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageAlive_2eproto() {
  delete MessageAlive::default_instance_;
  delete MessageAlive_reflection_;
}

void protobuf_AddDesc_MessageAlive_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022MessageAlive.proto\"\?\n\014MessageAlive\022\013\n\003"
    "CPU\030\001 \002(\005\022\016\n\006Memory\030\002 \002(\003\022\022\n\nBlockCount\030"
    "\003 \002(\003", 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageAlive.proto", &protobuf_RegisterTypes);
  MessageAlive::default_instance_ = new MessageAlive();
  MessageAlive::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageAlive_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageAlive_2eproto {
  StaticDescriptorInitializer_MessageAlive_2eproto() {
    protobuf_AddDesc_MessageAlive_2eproto();
  }
} static_descriptor_initializer_MessageAlive_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageAlive::kCPUFieldNumber;
const int MessageAlive::kMemoryFieldNumber;
const int MessageAlive::kBlockCountFieldNumber;
#endif  // !_MSC_VER

MessageAlive::MessageAlive()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageAlive)
}

void MessageAlive::InitAsDefaultInstance() {
}

MessageAlive::MessageAlive(const MessageAlive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageAlive)
}

void MessageAlive::SharedCtor() {
  _cached_size_ = 0;
  cpu_ = 0;
  memory_ = GOOGLE_LONGLONG(0);
  blockcount_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageAlive::~MessageAlive() {
  // @@protoc_insertion_point(destructor:MessageAlive)
  SharedDtor();
}

void MessageAlive::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageAlive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageAlive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageAlive_descriptor_;
}

const MessageAlive& MessageAlive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageAlive_2eproto();
  return *default_instance_;
}

MessageAlive* MessageAlive::default_instance_ = NULL;

MessageAlive* MessageAlive::New() const {
  return new MessageAlive;
}

void MessageAlive::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessageAlive*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(memory_, cpu_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageAlive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageAlive)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 CPU = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cpu_)));
          set_has_cpu();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_Memory;
        break;
      }

      // required int64 Memory = 2;
      case 2: {
        if (tag == 16) {
         parse_Memory:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &memory_)));
          set_has_memory();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_BlockCount;
        break;
      }

      // required int64 BlockCount = 3;
      case 3: {
        if (tag == 24) {
         parse_BlockCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &blockcount_)));
          set_has_blockcount();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageAlive)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageAlive)
  return false;
#undef DO_
}

void MessageAlive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageAlive)
  // required int32 CPU = 1;
  if (has_cpu()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cpu(), output);
  }

  // required int64 Memory = 2;
  if (has_memory()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->memory(), output);
  }

  // required int64 BlockCount = 3;
  if (has_blockcount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->blockcount(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageAlive)
}

::google::protobuf::uint8* MessageAlive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageAlive)
  // required int32 CPU = 1;
  if (has_cpu()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cpu(), target);
  }

  // required int64 Memory = 2;
  if (has_memory()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->memory(), target);
  }

  // required int64 BlockCount = 3;
  if (has_blockcount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->blockcount(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageAlive)
  return target;
}

int MessageAlive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 CPU = 1;
    if (has_cpu()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cpu());
    }

    // required int64 Memory = 2;
    if (has_memory()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->memory());
    }

    // required int64 BlockCount = 3;
    if (has_blockcount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->blockcount());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageAlive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageAlive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageAlive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageAlive::MergeFrom(const MessageAlive& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cpu()) {
      set_cpu(from.cpu());
    }
    if (from.has_memory()) {
      set_memory(from.memory());
    }
    if (from.has_blockcount()) {
      set_blockcount(from.blockcount());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageAlive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageAlive::CopyFrom(const MessageAlive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageAlive::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void MessageAlive::Swap(MessageAlive* other) {
  if (other != this) {
    std::swap(cpu_, other->cpu_);
    std::swap(memory_, other->memory_);
    std::swap(blockcount_, other->blockcount_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageAlive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageAlive_descriptor_;
  metadata.reflection = MessageAlive_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
