// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePrepareWrite.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessagePrepareWrite.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessagePrepareWrite_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessagePrepareWrite_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessagePrepareWrite_2eproto() {
  protobuf_AddDesc_MessagePrepareWrite_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessagePrepareWrite.proto");
  GOOGLE_CHECK(file != NULL);
  MessagePrepareWrite_descriptor_ = file->message_type(0);
  static const int MessagePrepareWrite_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, clientid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, isnew_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, fileoffset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, partid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, path_),
  };
  MessagePrepareWrite_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessagePrepareWrite_descriptor_,
      MessagePrepareWrite::default_instance_,
      MessagePrepareWrite_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessagePrepareWrite, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessagePrepareWrite));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessagePrepareWrite_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessagePrepareWrite_descriptor_, &MessagePrepareWrite::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessagePrepareWrite_2eproto() {
  delete MessagePrepareWrite::default_instance_;
  delete MessagePrepareWrite_reflection_;
}

void protobuf_AddDesc_MessagePrepareWrite_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031MessagePrepareWrite.proto\"w\n\023MessagePr"
    "epareWrite\022\020\n\010ClientId\030\001 \002(\003\022\r\n\005Index\030\002 "
    "\002(\003\022\r\n\005IsNew\030\003 \002(\010\022\022\n\nFileOffset\030\004 \001(\003\022\016"
    "\n\006PartId\030\005 \001(\003\022\014\n\004Path\030\006 \001(\t", 148);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessagePrepareWrite.proto", &protobuf_RegisterTypes);
  MessagePrepareWrite::default_instance_ = new MessagePrepareWrite();
  MessagePrepareWrite::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessagePrepareWrite_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessagePrepareWrite_2eproto {
  StaticDescriptorInitializer_MessagePrepareWrite_2eproto() {
    protobuf_AddDesc_MessagePrepareWrite_2eproto();
  }
} static_descriptor_initializer_MessagePrepareWrite_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessagePrepareWrite::kClientIdFieldNumber;
const int MessagePrepareWrite::kIndexFieldNumber;
const int MessagePrepareWrite::kIsNewFieldNumber;
const int MessagePrepareWrite::kFileOffsetFieldNumber;
const int MessagePrepareWrite::kPartIdFieldNumber;
const int MessagePrepareWrite::kPathFieldNumber;
#endif  // !_MSC_VER

MessagePrepareWrite::MessagePrepareWrite()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessagePrepareWrite)
}

void MessagePrepareWrite::InitAsDefaultInstance() {
}

MessagePrepareWrite::MessagePrepareWrite(const MessagePrepareWrite& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessagePrepareWrite)
}

void MessagePrepareWrite::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  clientid_ = GOOGLE_LONGLONG(0);
  index_ = GOOGLE_LONGLONG(0);
  isnew_ = false;
  fileoffset_ = GOOGLE_LONGLONG(0);
  partid_ = GOOGLE_LONGLONG(0);
  path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessagePrepareWrite::~MessagePrepareWrite() {
  // @@protoc_insertion_point(destructor:MessagePrepareWrite)
  SharedDtor();
}

void MessagePrepareWrite::SharedDtor() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (this != default_instance_) {
  }
}

void MessagePrepareWrite::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessagePrepareWrite::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessagePrepareWrite_descriptor_;
}

const MessagePrepareWrite& MessagePrepareWrite::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessagePrepareWrite_2eproto();
  return *default_instance_;
}

MessagePrepareWrite* MessagePrepareWrite::default_instance_ = NULL;

MessagePrepareWrite* MessagePrepareWrite::New() const {
  return new MessagePrepareWrite;
}

void MessagePrepareWrite::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessagePrepareWrite*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(clientid_, partid_);
    isnew_ = false;
    if (has_path()) {
      if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        path_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessagePrepareWrite::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessagePrepareWrite)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 ClientId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &clientid_)));
          set_has_clientid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_Index;
        break;
      }

      // required int64 Index = 2;
      case 2: {
        if (tag == 16) {
         parse_Index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &index_)));
          set_has_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_IsNew;
        break;
      }

      // required bool IsNew = 3;
      case 3: {
        if (tag == 24) {
         parse_IsNew:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isnew_)));
          set_has_isnew();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_FileOffset;
        break;
      }

      // optional int64 FileOffset = 4;
      case 4: {
        if (tag == 32) {
         parse_FileOffset:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &fileoffset_)));
          set_has_fileoffset();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_PartId;
        break;
      }

      // optional int64 PartId = 5;
      case 5: {
        if (tag == 40) {
         parse_PartId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &partid_)));
          set_has_partid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_Path;
        break;
      }

      // optional string Path = 6;
      case 6: {
        if (tag == 50) {
         parse_Path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessagePrepareWrite)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessagePrepareWrite)
  return false;
#undef DO_
}

void MessagePrepareWrite::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessagePrepareWrite)
  // required int64 ClientId = 1;
  if (has_clientid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->clientid(), output);
  }

  // required int64 Index = 2;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->index(), output);
  }

  // required bool IsNew = 3;
  if (has_isnew()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isnew(), output);
  }

  // optional int64 FileOffset = 4;
  if (has_fileoffset()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->fileoffset(), output);
  }

  // optional int64 PartId = 5;
  if (has_partid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->partid(), output);
  }

  // optional string Path = 6;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->path(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessagePrepareWrite)
}

::google::protobuf::uint8* MessagePrepareWrite::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessagePrepareWrite)
  // required int64 ClientId = 1;
  if (has_clientid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->clientid(), target);
  }

  // required int64 Index = 2;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->index(), target);
  }

  // required bool IsNew = 3;
  if (has_isnew()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isnew(), target);
  }

  // optional int64 FileOffset = 4;
  if (has_fileoffset()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->fileoffset(), target);
  }

  // optional int64 PartId = 5;
  if (has_partid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->partid(), target);
  }

  // optional string Path = 6;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->path(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessagePrepareWrite)
  return target;
}

int MessagePrepareWrite::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 ClientId = 1;
    if (has_clientid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->clientid());
    }

    // required int64 Index = 2;
    if (has_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->index());
    }

    // required bool IsNew = 3;
    if (has_isnew()) {
      total_size += 1 + 1;
    }

    // optional int64 FileOffset = 4;
    if (has_fileoffset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->fileoffset());
    }

    // optional int64 PartId = 5;
    if (has_partid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->partid());
    }

    // optional string Path = 6;
    if (has_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->path());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessagePrepareWrite::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessagePrepareWrite* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessagePrepareWrite*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessagePrepareWrite::MergeFrom(const MessagePrepareWrite& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_clientid()) {
      set_clientid(from.clientid());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
    if (from.has_isnew()) {
      set_isnew(from.isnew());
    }
    if (from.has_fileoffset()) {
      set_fileoffset(from.fileoffset());
    }
    if (from.has_partid()) {
      set_partid(from.partid());
    }
    if (from.has_path()) {
      set_path(from.path());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessagePrepareWrite::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessagePrepareWrite::CopyFrom(const MessagePrepareWrite& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessagePrepareWrite::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void MessagePrepareWrite::Swap(MessagePrepareWrite* other) {
  if (other != this) {
    std::swap(clientid_, other->clientid_);
    std::swap(index_, other->index_);
    std::swap(isnew_, other->isnew_);
    std::swap(fileoffset_, other->fileoffset_);
    std::swap(partid_, other->partid_);
    std::swap(path_, other->path_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessagePrepareWrite::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessagePrepareWrite_descriptor_;
  metadata.reflection = MessagePrepareWrite_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
