// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageSyncBlock.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageSyncBlock.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageSyncBlock_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageSyncBlock_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageSyncBlock_2eproto() {
  protobuf_AddDesc_MessageSyncBlock_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageSyncBlock.proto");
  GOOGLE_CHECK(file != NULL);
  MessageSyncBlock_descriptor_ = file->message_type(0);
  static const int MessageSyncBlock_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageSyncBlock, blockcount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageSyncBlock, blocks_),
  };
  MessageSyncBlock_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageSyncBlock_descriptor_,
      MessageSyncBlock::default_instance_,
      MessageSyncBlock_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageSyncBlock, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageSyncBlock, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageSyncBlock));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageSyncBlock_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageSyncBlock_descriptor_, &MessageSyncBlock::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageSyncBlock_2eproto() {
  delete MessageSyncBlock::default_instance_;
  delete MessageSyncBlock_reflection_;
}

void protobuf_AddDesc_MessageSyncBlock_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_MessageBlockMeta_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026MessageSyncBlock.proto\032\026MessageBlockMe"
    "ta.proto\"I\n\020MessageSyncBlock\022\022\n\nBlockCou"
    "nt\030\001 \002(\003\022!\n\006Blocks\030\002 \003(\0132\021.MessageBlockM"
    "eta", 123);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageSyncBlock.proto", &protobuf_RegisterTypes);
  MessageSyncBlock::default_instance_ = new MessageSyncBlock();
  MessageSyncBlock::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageSyncBlock_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageSyncBlock_2eproto {
  StaticDescriptorInitializer_MessageSyncBlock_2eproto() {
    protobuf_AddDesc_MessageSyncBlock_2eproto();
  }
} static_descriptor_initializer_MessageSyncBlock_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageSyncBlock::kBlockCountFieldNumber;
const int MessageSyncBlock::kBlocksFieldNumber;
#endif  // !_MSC_VER

MessageSyncBlock::MessageSyncBlock()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageSyncBlock)
}

void MessageSyncBlock::InitAsDefaultInstance() {
}

MessageSyncBlock::MessageSyncBlock(const MessageSyncBlock& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageSyncBlock)
}

void MessageSyncBlock::SharedCtor() {
  _cached_size_ = 0;
  blockcount_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageSyncBlock::~MessageSyncBlock() {
  // @@protoc_insertion_point(destructor:MessageSyncBlock)
  SharedDtor();
}

void MessageSyncBlock::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageSyncBlock::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageSyncBlock::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageSyncBlock_descriptor_;
}

const MessageSyncBlock& MessageSyncBlock::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageSyncBlock_2eproto();
  return *default_instance_;
}

MessageSyncBlock* MessageSyncBlock::default_instance_ = NULL;

MessageSyncBlock* MessageSyncBlock::New() const {
  return new MessageSyncBlock;
}

void MessageSyncBlock::Clear() {
  blockcount_ = GOOGLE_LONGLONG(0);
  blocks_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageSyncBlock::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageSyncBlock)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 BlockCount = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &blockcount_)));
          set_has_blockcount();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Blocks;
        break;
      }

      // repeated .MessageBlockMeta Blocks = 2;
      case 2: {
        if (tag == 18) {
         parse_Blocks:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_blocks()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Blocks;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageSyncBlock)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageSyncBlock)
  return false;
#undef DO_
}

void MessageSyncBlock::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageSyncBlock)
  // required int64 BlockCount = 1;
  if (has_blockcount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->blockcount(), output);
  }

  // repeated .MessageBlockMeta Blocks = 2;
  for (int i = 0; i < this->blocks_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->blocks(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageSyncBlock)
}

::google::protobuf::uint8* MessageSyncBlock::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageSyncBlock)
  // required int64 BlockCount = 1;
  if (has_blockcount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->blockcount(), target);
  }

  // repeated .MessageBlockMeta Blocks = 2;
  for (int i = 0; i < this->blocks_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->blocks(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageSyncBlock)
  return target;
}

int MessageSyncBlock::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 BlockCount = 1;
    if (has_blockcount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->blockcount());
    }

  }
  // repeated .MessageBlockMeta Blocks = 2;
  total_size += 1 * this->blocks_size();
  for (int i = 0; i < this->blocks_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->blocks(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageSyncBlock::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageSyncBlock* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageSyncBlock*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageSyncBlock::MergeFrom(const MessageSyncBlock& from) {
  GOOGLE_CHECK_NE(&from, this);
  blocks_.MergeFrom(from.blocks_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_blockcount()) {
      set_blockcount(from.blockcount());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageSyncBlock::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageSyncBlock::CopyFrom(const MessageSyncBlock& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageSyncBlock::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->blocks())) return false;
  return true;
}

void MessageSyncBlock::Swap(MessageSyncBlock* other) {
  if (other != this) {
    std::swap(blockcount_, other->blockcount_);
    blocks_.Swap(&other->blocks_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageSyncBlock::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageSyncBlock_descriptor_;
  metadata.reflection = MessageSyncBlock_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
