// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePrepareRead.proto

#ifndef PROTOBUF_MessagePrepareRead_2eproto__INCLUDED
#define PROTOBUF_MessagePrepareRead_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessagePrepareRead_2eproto();
void protobuf_AssignDesc_MessagePrepareRead_2eproto();
void protobuf_ShutdownFile_MessagePrepareRead_2eproto();

class MessagePrepareRead;

// ===================================================================

class MessagePrepareRead : public ::google::protobuf::Message {
 public:
  MessagePrepareRead();
  virtual ~MessagePrepareRead();

  MessagePrepareRead(const MessagePrepareRead& from);

  inline MessagePrepareRead& operator=(const MessagePrepareRead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessagePrepareRead& default_instance();

  void Swap(MessagePrepareRead* other);

  // implements Message ----------------------------------------------

  MessagePrepareRead* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessagePrepareRead& from);
  void MergeFrom(const MessagePrepareRead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 ClientId = 1;
  inline bool has_clientid() const;
  inline void clear_clientid();
  static const int kClientIdFieldNumber = 1;
  inline ::google::protobuf::int64 clientid() const;
  inline void set_clientid(::google::protobuf::int64 value);

  // required int64 Index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessagePrepareRead)
 private:
  inline void set_has_clientid();
  inline void clear_has_clientid();
  inline void set_has_index();
  inline void clear_has_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 clientid_;
  ::google::protobuf::int64 index_;
  friend void  protobuf_AddDesc_MessagePrepareRead_2eproto();
  friend void protobuf_AssignDesc_MessagePrepareRead_2eproto();
  friend void protobuf_ShutdownFile_MessagePrepareRead_2eproto();

  void InitAsDefaultInstance();
  static MessagePrepareRead* default_instance_;
};
// ===================================================================


// ===================================================================

// MessagePrepareRead

// required int64 ClientId = 1;
inline bool MessagePrepareRead::has_clientid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessagePrepareRead::set_has_clientid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessagePrepareRead::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessagePrepareRead::clear_clientid() {
  clientid_ = GOOGLE_LONGLONG(0);
  clear_has_clientid();
}
inline ::google::protobuf::int64 MessagePrepareRead::clientid() const {
  // @@protoc_insertion_point(field_get:MessagePrepareRead.ClientId)
  return clientid_;
}
inline void MessagePrepareRead::set_clientid(::google::protobuf::int64 value) {
  set_has_clientid();
  clientid_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareRead.ClientId)
}

// required int64 Index = 2;
inline bool MessagePrepareRead::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessagePrepareRead::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessagePrepareRead::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessagePrepareRead::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessagePrepareRead::index() const {
  // @@protoc_insertion_point(field_get:MessagePrepareRead.Index)
  return index_;
}
inline void MessagePrepareRead::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareRead.Index)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessagePrepareRead_2eproto__INCLUDED
