// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageOpenACK.proto

#ifndef PROTOBUF_MessageOpenACK_2eproto__INCLUDED
#define PROTOBUF_MessageOpenACK_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageOpenACK_2eproto();
void protobuf_AssignDesc_MessageOpenACK_2eproto();
void protobuf_ShutdownFile_MessageOpenACK_2eproto();

class MessageOpenACK;

// ===================================================================

class MessageOpenACK : public ::google::protobuf::Message {
 public:
  MessageOpenACK();
  virtual ~MessageOpenACK();

  MessageOpenACK(const MessageOpenACK& from);

  inline MessageOpenACK& operator=(const MessageOpenACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageOpenACK& default_instance();

  void Swap(MessageOpenACK* other);

  // implements Message ----------------------------------------------

  MessageOpenACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageOpenACK& from);
  void MergeFrom(const MessageOpenACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required int32 Code = 2;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 2;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // required string Message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:MessageOpenACK)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::std::string* message_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_MessageOpenACK_2eproto();
  friend void protobuf_AssignDesc_MessageOpenACK_2eproto();
  friend void protobuf_ShutdownFile_MessageOpenACK_2eproto();

  void InitAsDefaultInstance();
  static MessageOpenACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageOpenACK

// required string Token = 1;
inline bool MessageOpenACK::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageOpenACK::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageOpenACK::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageOpenACK::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageOpenACK::token() const {
  // @@protoc_insertion_point(field_get:MessageOpenACK.Token)
  return *token_;
}
inline void MessageOpenACK::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageOpenACK.Token)
}
inline void MessageOpenACK::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageOpenACK.Token)
}
inline void MessageOpenACK::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageOpenACK.Token)
}
inline ::std::string* MessageOpenACK::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageOpenACK.Token)
  return token_;
}
inline ::std::string* MessageOpenACK::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageOpenACK::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageOpenACK.Token)
}

// required int32 Code = 2;
inline bool MessageOpenACK::has_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageOpenACK::set_has_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageOpenACK::clear_has_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageOpenACK::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MessageOpenACK::code() const {
  // @@protoc_insertion_point(field_get:MessageOpenACK.Code)
  return code_;
}
inline void MessageOpenACK::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MessageOpenACK.Code)
}

// required string Message = 3;
inline bool MessageOpenACK::has_message() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageOpenACK::set_has_message() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageOpenACK::clear_has_message() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageOpenACK::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& MessageOpenACK::message() const {
  // @@protoc_insertion_point(field_get:MessageOpenACK.Message)
  return *message_;
}
inline void MessageOpenACK::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:MessageOpenACK.Message)
}
inline void MessageOpenACK::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageOpenACK.Message)
}
inline void MessageOpenACK::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageOpenACK.Message)
}
inline ::std::string* MessageOpenACK::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageOpenACK.Message)
  return message_;
}
inline ::std::string* MessageOpenACK::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageOpenACK::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageOpenACK.Message)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageOpenACK_2eproto__INCLUDED
