// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageOpenFile.proto

#ifndef PROTOBUF_MessageOpenFile_2eproto__INCLUDED
#define PROTOBUF_MessageOpenFile_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageOpenFile_2eproto();
void protobuf_AssignDesc_MessageOpenFile_2eproto();
void protobuf_ShutdownFile_MessageOpenFile_2eproto();

class MessageOpenFile;

// ===================================================================

class MessageOpenFile : public ::google::protobuf::Message {
 public:
  MessageOpenFile();
  virtual ~MessageOpenFile();

  MessageOpenFile(const MessageOpenFile& from);

  inline MessageOpenFile& operator=(const MessageOpenFile& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageOpenFile& default_instance();

  void Swap(MessageOpenFile* other);

  // implements Message ----------------------------------------------

  MessageOpenFile* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageOpenFile& from);
  void MergeFrom(const MessageOpenFile& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Path = 1;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 1;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // required int32 Mode = 2;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 2;
  inline ::google::protobuf::int32 mode() const;
  inline void set_mode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageOpenFile)
 private:
  inline void set_has_path();
  inline void clear_has_path();
  inline void set_has_mode();
  inline void clear_has_mode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* path_;
  ::google::protobuf::int32 mode_;
  friend void  protobuf_AddDesc_MessageOpenFile_2eproto();
  friend void protobuf_AssignDesc_MessageOpenFile_2eproto();
  friend void protobuf_ShutdownFile_MessageOpenFile_2eproto();

  void InitAsDefaultInstance();
  static MessageOpenFile* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageOpenFile

// required string Path = 1;
inline bool MessageOpenFile::has_path() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageOpenFile::set_has_path() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageOpenFile::clear_has_path() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageOpenFile::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& MessageOpenFile::path() const {
  // @@protoc_insertion_point(field_get:MessageOpenFile.Path)
  return *path_;
}
inline void MessageOpenFile::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:MessageOpenFile.Path)
}
inline void MessageOpenFile::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageOpenFile.Path)
}
inline void MessageOpenFile::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageOpenFile.Path)
}
inline ::std::string* MessageOpenFile::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageOpenFile.Path)
  return path_;
}
inline ::std::string* MessageOpenFile::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageOpenFile::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageOpenFile.Path)
}

// required int32 Mode = 2;
inline bool MessageOpenFile::has_mode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageOpenFile::set_has_mode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageOpenFile::clear_has_mode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageOpenFile::clear_mode() {
  mode_ = 0;
  clear_has_mode();
}
inline ::google::protobuf::int32 MessageOpenFile::mode() const {
  // @@protoc_insertion_point(field_get:MessageOpenFile.Mode)
  return mode_;
}
inline void MessageOpenFile::set_mode(::google::protobuf::int32 value) {
  set_has_mode();
  mode_ = value;
  // @@protoc_insertion_point(field_set:MessageOpenFile.Mode)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageOpenFile_2eproto__INCLUDED
