// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePrepareWrite.proto

#ifndef PROTOBUF_MessagePrepareWrite_2eproto__INCLUDED
#define PROTOBUF_MessagePrepareWrite_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessagePrepareWrite_2eproto();
void protobuf_AssignDesc_MessagePrepareWrite_2eproto();
void protobuf_ShutdownFile_MessagePrepareWrite_2eproto();

class MessagePrepareWrite;

// ===================================================================

class MessagePrepareWrite : public ::google::protobuf::Message {
 public:
  MessagePrepareWrite();
  virtual ~MessagePrepareWrite();

  MessagePrepareWrite(const MessagePrepareWrite& from);

  inline MessagePrepareWrite& operator=(const MessagePrepareWrite& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessagePrepareWrite& default_instance();

  void Swap(MessagePrepareWrite* other);

  // implements Message ----------------------------------------------

  MessagePrepareWrite* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessagePrepareWrite& from);
  void MergeFrom(const MessagePrepareWrite& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 ClientId = 1;
  inline bool has_clientid() const;
  inline void clear_clientid();
  static const int kClientIdFieldNumber = 1;
  inline ::google::protobuf::int64 clientid() const;
  inline void set_clientid(::google::protobuf::int64 value);

  // required int64 Index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // optional int64 FileOffset = 3;
  inline bool has_fileoffset() const;
  inline void clear_fileoffset();
  static const int kFileOffsetFieldNumber = 3;
  inline ::google::protobuf::int64 fileoffset() const;
  inline void set_fileoffset(::google::protobuf::int64 value);

  // optional int64 PartId = 4;
  inline bool has_partid() const;
  inline void clear_partid();
  static const int kPartIdFieldNumber = 4;
  inline ::google::protobuf::int64 partid() const;
  inline void set_partid(::google::protobuf::int64 value);

  // optional string Path = 5;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 5;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:MessagePrepareWrite)
 private:
  inline void set_has_clientid();
  inline void clear_has_clientid();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_fileoffset();
  inline void clear_has_fileoffset();
  inline void set_has_partid();
  inline void clear_has_partid();
  inline void set_has_path();
  inline void clear_has_path();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 clientid_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int64 fileoffset_;
  ::google::protobuf::int64 partid_;
  ::std::string* path_;
  friend void  protobuf_AddDesc_MessagePrepareWrite_2eproto();
  friend void protobuf_AssignDesc_MessagePrepareWrite_2eproto();
  friend void protobuf_ShutdownFile_MessagePrepareWrite_2eproto();

  void InitAsDefaultInstance();
  static MessagePrepareWrite* default_instance_;
};
// ===================================================================


// ===================================================================

// MessagePrepareWrite

// required int64 ClientId = 1;
inline bool MessagePrepareWrite::has_clientid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessagePrepareWrite::set_has_clientid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessagePrepareWrite::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessagePrepareWrite::clear_clientid() {
  clientid_ = GOOGLE_LONGLONG(0);
  clear_has_clientid();
}
inline ::google::protobuf::int64 MessagePrepareWrite::clientid() const {
  // @@protoc_insertion_point(field_get:MessagePrepareWrite.ClientId)
  return clientid_;
}
inline void MessagePrepareWrite::set_clientid(::google::protobuf::int64 value) {
  set_has_clientid();
  clientid_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareWrite.ClientId)
}

// required int64 Index = 2;
inline bool MessagePrepareWrite::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessagePrepareWrite::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessagePrepareWrite::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessagePrepareWrite::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessagePrepareWrite::index() const {
  // @@protoc_insertion_point(field_get:MessagePrepareWrite.Index)
  return index_;
}
inline void MessagePrepareWrite::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareWrite.Index)
}

// optional int64 FileOffset = 3;
inline bool MessagePrepareWrite::has_fileoffset() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessagePrepareWrite::set_has_fileoffset() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessagePrepareWrite::clear_has_fileoffset() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessagePrepareWrite::clear_fileoffset() {
  fileoffset_ = GOOGLE_LONGLONG(0);
  clear_has_fileoffset();
}
inline ::google::protobuf::int64 MessagePrepareWrite::fileoffset() const {
  // @@protoc_insertion_point(field_get:MessagePrepareWrite.FileOffset)
  return fileoffset_;
}
inline void MessagePrepareWrite::set_fileoffset(::google::protobuf::int64 value) {
  set_has_fileoffset();
  fileoffset_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareWrite.FileOffset)
}

// optional int64 PartId = 4;
inline bool MessagePrepareWrite::has_partid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessagePrepareWrite::set_has_partid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessagePrepareWrite::clear_has_partid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessagePrepareWrite::clear_partid() {
  partid_ = GOOGLE_LONGLONG(0);
  clear_has_partid();
}
inline ::google::protobuf::int64 MessagePrepareWrite::partid() const {
  // @@protoc_insertion_point(field_get:MessagePrepareWrite.PartId)
  return partid_;
}
inline void MessagePrepareWrite::set_partid(::google::protobuf::int64 value) {
  set_has_partid();
  partid_ = value;
  // @@protoc_insertion_point(field_set:MessagePrepareWrite.PartId)
}

// optional string Path = 5;
inline bool MessagePrepareWrite::has_path() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessagePrepareWrite::set_has_path() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessagePrepareWrite::clear_has_path() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessagePrepareWrite::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& MessagePrepareWrite::path() const {
  // @@protoc_insertion_point(field_get:MessagePrepareWrite.Path)
  return *path_;
}
inline void MessagePrepareWrite::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:MessagePrepareWrite.Path)
}
inline void MessagePrepareWrite::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessagePrepareWrite.Path)
}
inline void MessagePrepareWrite::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessagePrepareWrite.Path)
}
inline ::std::string* MessagePrepareWrite::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessagePrepareWrite.Path)
  return path_;
}
inline ::std::string* MessagePrepareWrite::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessagePrepareWrite::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessagePrepareWrite.Path)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessagePrepareWrite_2eproto__INCLUDED
