// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBlockAccept.proto

#ifndef PROTOBUF_MessageBlockAccept_2eproto__INCLUDED
#define PROTOBUF_MessageBlockAccept_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageBlockAccept_2eproto();
void protobuf_AssignDesc_MessageBlockAccept_2eproto();
void protobuf_ShutdownFile_MessageBlockAccept_2eproto();

class MessageBlockAccept;

// ===================================================================

class MessageBlockAccept : public ::google::protobuf::Message {
 public:
  MessageBlockAccept();
  virtual ~MessageBlockAccept();

  MessageBlockAccept(const MessageBlockAccept& from);

  inline MessageBlockAccept& operator=(const MessageBlockAccept& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageBlockAccept& default_instance();

  void Swap(MessageBlockAccept* other);

  // implements Message ----------------------------------------------

  MessageBlockAccept* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageBlockAccept& from);
  void MergeFrom(const MessageBlockAccept& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required int64 Size = 2;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 2;
  inline ::google::protobuf::int64 size() const;
  inline void set_size(::google::protobuf::int64 value);

  // required int64 NextOffset = 3;
  inline bool has_nextoffset() const;
  inline void clear_nextoffset();
  static const int kNextOffsetFieldNumber = 3;
  inline ::google::protobuf::int64 nextoffset() const;
  inline void set_nextoffset(::google::protobuf::int64 value);

  // required int64 NextSize = 4;
  inline bool has_nextsize() const;
  inline void clear_nextsize();
  static const int kNextSizeFieldNumber = 4;
  inline ::google::protobuf::int64 nextsize() const;
  inline void set_nextsize(::google::protobuf::int64 value);

  // required int64 Checksum = 5;
  inline bool has_checksum() const;
  inline void clear_checksum();
  static const int kChecksumFieldNumber = 5;
  inline ::google::protobuf::int64 checksum() const;
  inline void set_checksum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageBlockAccept)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_nextoffset();
  inline void clear_has_nextoffset();
  inline void set_has_nextsize();
  inline void clear_has_nextsize();
  inline void set_has_checksum();
  inline void clear_has_checksum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::google::protobuf::int64 size_;
  ::google::protobuf::int64 nextoffset_;
  ::google::protobuf::int64 nextsize_;
  ::google::protobuf::int64 checksum_;
  friend void  protobuf_AddDesc_MessageBlockAccept_2eproto();
  friend void protobuf_AssignDesc_MessageBlockAccept_2eproto();
  friend void protobuf_ShutdownFile_MessageBlockAccept_2eproto();

  void InitAsDefaultInstance();
  static MessageBlockAccept* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageBlockAccept

// required string Token = 1;
inline bool MessageBlockAccept::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageBlockAccept::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageBlockAccept::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageBlockAccept::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageBlockAccept::token() const {
  // @@protoc_insertion_point(field_get:MessageBlockAccept.Token)
  return *token_;
}
inline void MessageBlockAccept::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageBlockAccept.Token)
}
inline void MessageBlockAccept::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageBlockAccept.Token)
}
inline void MessageBlockAccept::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageBlockAccept.Token)
}
inline ::std::string* MessageBlockAccept::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageBlockAccept.Token)
  return token_;
}
inline ::std::string* MessageBlockAccept::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageBlockAccept::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageBlockAccept.Token)
}

// required int64 Size = 2;
inline bool MessageBlockAccept::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageBlockAccept::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageBlockAccept::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageBlockAccept::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::int64 MessageBlockAccept::size() const {
  // @@protoc_insertion_point(field_get:MessageBlockAccept.Size)
  return size_;
}
inline void MessageBlockAccept::set_size(::google::protobuf::int64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:MessageBlockAccept.Size)
}

// required int64 NextOffset = 3;
inline bool MessageBlockAccept::has_nextoffset() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageBlockAccept::set_has_nextoffset() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageBlockAccept::clear_has_nextoffset() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageBlockAccept::clear_nextoffset() {
  nextoffset_ = GOOGLE_LONGLONG(0);
  clear_has_nextoffset();
}
inline ::google::protobuf::int64 MessageBlockAccept::nextoffset() const {
  // @@protoc_insertion_point(field_get:MessageBlockAccept.NextOffset)
  return nextoffset_;
}
inline void MessageBlockAccept::set_nextoffset(::google::protobuf::int64 value) {
  set_has_nextoffset();
  nextoffset_ = value;
  // @@protoc_insertion_point(field_set:MessageBlockAccept.NextOffset)
}

// required int64 NextSize = 4;
inline bool MessageBlockAccept::has_nextsize() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageBlockAccept::set_has_nextsize() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageBlockAccept::clear_has_nextsize() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageBlockAccept::clear_nextsize() {
  nextsize_ = GOOGLE_LONGLONG(0);
  clear_has_nextsize();
}
inline ::google::protobuf::int64 MessageBlockAccept::nextsize() const {
  // @@protoc_insertion_point(field_get:MessageBlockAccept.NextSize)
  return nextsize_;
}
inline void MessageBlockAccept::set_nextsize(::google::protobuf::int64 value) {
  set_has_nextsize();
  nextsize_ = value;
  // @@protoc_insertion_point(field_set:MessageBlockAccept.NextSize)
}

// required int64 Checksum = 5;
inline bool MessageBlockAccept::has_checksum() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageBlockAccept::set_has_checksum() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageBlockAccept::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageBlockAccept::clear_checksum() {
  checksum_ = GOOGLE_LONGLONG(0);
  clear_has_checksum();
}
inline ::google::protobuf::int64 MessageBlockAccept::checksum() const {
  // @@protoc_insertion_point(field_get:MessageBlockAccept.Checksum)
  return checksum_;
}
inline void MessageBlockAccept::set_checksum(::google::protobuf::int64 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:MessageBlockAccept.Checksum)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageBlockAccept_2eproto__INCLUDED
